[package]
name = "collabo-git-lfs"
version = "3.8.0"
description = "Git LFS written again in Rust for the guest"
edition.workspace = true
license.workspace = true
publish.workspace = true
build = "build.rs"

[[bin]]
name = "git-lfs"
path = "src/main.rs"

[dependencies]
libc = "0.2"
sha2 = "0.11"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
regex = "1"
sha1 = "0.11"
flate2 = { version = "1", default-features = false, features = ["rust_backend"] }
structured-zstd = { version = "0.0.58", default-features = false, features = ["std"] }
