"""Differential tests of our jq against the original (built from jq's development tree, which
ours follows): each case runs both with the same arguments, input and environment, and
compares exit status, stdout and stderr. jq's own test suites (tests/*.test, shtest) are the
other half: `jq --run-tests` runs them on ours.

    python3 jq-difftest.py OUR_JQ REF_JQ [JQ_SOURCE_TREE]

JQ_SOURCE_TREE (default /opt/workspace/org/jq) provides tests/modules for the module cases.
Known, intended differences are listed in KNOWN."""
import os, subprocess, sys, tempfile

OURS, REF = sys.argv[1], sys.argv[2]
TREE = sys.argv[3] if len(sys.argv) > 3 else "/opt/workspace/org/jq"
MODS = f"{TREE}/tests/modules"

DOC = '{"a":1,"b":[1,2,{"c":"x"}],"s":"Hello, World","n":null,"t":true,"f":1.5,"big":100000000000000000000001,"e":[],"o":{}}'
ARR = '[3,1,"b","a",null,true,false,[1],{"k":1},2.5,-1,1e100]'
OBJS = '[{"k":"x","v":1},{"k":"y","v":2},{"k":"x","v":3},{"k":null,"v":4}]'

# Filters run with -c on each of the inputs.
FILTERS = [
    ".", ".a", ".b[2].c", ".b[]", ".b[-1]", ".b[1:]", ".b[:-1]", ".s[0:5]", ".s[-5:]", ".[]?", "..", "[..]|length",
    "keys", "keys_unsorted", "to_entries", "with_entries(.value |= tostring)", "paths", "[paths(type == \"number\")]",
    "[leaf_paths]", "tostream", "[tostream] | fromstream(.[])", "getpath([\"b\",2,\"c\"])", "[getpath([\"x\",\"y\"])]",
    "delpaths([[\"a\"],[\"b\",0]])", "del(.b[0,2])", "del(.. | nulls)", "to_entries | from_entries", "length", "utf8bytelength",
    "type", "map_values(type)", "[.[] | type]", "add", "any", "all", "flatten", "flatten(1)", "range(5)", "[range(0;10;3)]",
    "[range(5;0;-2)]", "floor", "sqrt", "tostring", "tojson", "tojson | fromjson", "ascii_downcase", "ascii_upcase",
    "explode", "explode | implode", "ltrimstr(\"Hel\")", "rtrimstr(\"ld\")", "trimstr(\"H\")", "startswith(\"He\")", "split(\", \")",
    "split(\"l\"; null)", "test(\"world\"; \"i\")", "[match(\"o\"; \"g\").offset]", "capture(\"(?<first>\\\\w+), (?<second>\\\\w+)\")",
    "[scan(\"l+\")]", "sub(\"(?<x>l+)\"; \"<\\(.x)>\")", "gsub(\"o\"; \"0\")", "gsub(\"\"; \"-\")", "[splits(\", *\")]", "ascii",
    "@text", "@json", "@html", "@uri", "@csv", "@tsv", "@sh", "@base64", "@base64d", "@base32", "@base32d", "@urid",
    "@json \"x\\(.)y\"", "@base64 \"\\(.)\"", "tojson | @sh", "sort", "sort_by(type)", "group_by(type)", "unique", "unique_by(type)",
    "min", "max", "min_by(.v)", "max_by(.v)", "group_by(.k) | map({k: .[0].k, n: length})", "INDEX(.k)", "reverse", "indices(1)",
    "index(\"o\")", "rindex(\"o\")", "inside([1,2,3])", "contains([1])", "contains({a:1})", "contains(\"World\")", "has(\"a\")",
    "has(0)", "in({\"a\":1})", "[.[] | numbers]", "[.[] | strings]", "[.[] | iterables]", "[.[] | scalars]", "map(select(. != null))",
    "first", "last", "nth(1)", "first(range(10;0;-1))", "[limit(3; .[]?)]", "[skip(2; .[]?)]", "until(. > 100; . * 2)",
    "[while(. < 100; . * 2 + 1)]", "[repeat(. * 2; . < 10)]?", "[recurse(if . < 3 then . + 1 else empty end)]", "env | type",
    "$ENV | type", "input_filename", "$__loc__", "splits(\"a\")?", "tojson | length", "transpose", "combinations | tostring",
    "[combinations(2)]", "walk(if type == \"number\" then . + 1 else . end)", "pick(.a, .b[1])", "debug", "debug(\"msg\")",
    "stderr", "input_line_number", "getpath([\"a\"]) as $x | $x", ". as [$a, $b] | [$a, $b]", ". as {a: $x} ?// [$x] | $x",
    "reduce .[]? as $x (0; . + 1)", "foreach .[]? as $x (0; . + 1; [$x, .])", "label $f | .[]? | ., break $f", "try error catch .",
    "try error(\"x\") catch .", "try error({a: 1}) catch .a", "error", "error(null)", "error({a: 1})", ".a = 5", ".a |= . + 1",
    ".b[0] += 10", ".x //= 3", ".b[1:] = [9]", ".. |= (if type == \"number\" then . + 1 else . end)", "to_entries[0].key",
    "isvalid(.a)?", "splits", "ltrimstr(1)", "tostring | ascii_downcase", "infinite", "-infinite", "nan | isnan", "[nan] | sort",
    "[.[]? | isinfinite]", "1e1000", "-1e1000", "100000000000000000000001", "100000000000000000000001 + 0", ".big", ".big + 1",
    "[.big] | tojson", "1.000", "[1.000, 1.0, 1e2, 0.0001, 1e-5, 123456789012345678]", "3.0 == 3", "-0", "[-0.0]", "0.1 + 0.2",
    "1 / 3", "10 % 3", "-10 % 3", "5 % -2", "1 % 0", "[limit(3; repeat(1))]", "significand?", "gamma?", "frexp?", "modf?",
    "ldexp(.; 2)?", "now | type", "\"2015-03-05T23:51:47Z\" | fromdate", "1425599507 | todate", "1425599507 | gmtime",
    "1425599507 | gmtime | mktime", "1425599507 | strftime(\"%A, %B %d, %Y %j %U %e\")", "\"10:15 2015-03-05\" | strptime(\"%H:%M %Y-%m-%d\")",
    "\"2015-03-05T23:51:47Z\" | strptime(\"%Y-%m-%dT%H:%M:%SZ\") | mktime", "1425599507 | localtime | mktime", "1425599507 | strflocaltime(\"%H %Z\")",
    "\"2015-03-05\" | fromdateiso8601", "\"2015-W10-4\" | fromdateiso8601", "\"bad\" | fromdate", "todate?", "getpath([0,1])?",
    "splits(1)?", "implode?", "[.[]?] | implode?", "tojson | fromjson | tojson", "\"[1,2\" | fromjson", "\"1 2\" | fromjson",
    "\"nan\" | fromjson", "\"NaN\" | tonumber", "\" 1\" | tonumber", "\"0x10\" | tonumber", "\"1e3\" | tonumber", "tonumber?",
    "toboolean?", "\"true\" | toboolean", "abs?", "-5 | abs", "trim?", "\"  a b  \" | trim, ltrim, rtrim", "have_decnum",
    "have_literal_numbers", "builtins | length > 100", "\"abc\" | .[1:2]", "\"aé😀\" | length, utf8bytelength, explode",
    "\"\\u00e9\" | @uri", "[1,[2,[3,[4]]]] | flatten(2)", "{} | .a.b.c = 1", "[] | .[3] = 1", "null | .[-1] = 1", "[1] | .[-2] = 1",
    "{\"a\":[1,2]} | .a[1:] |= map(. * 10)", "[1,2,3] | IN(2)", "[1,2,3] | IN(.[]; 2, 5)", "ascii(65)?", "@text \"a\\(1+1)b\"",
    "{a:1} * {a:{b:2}}", "{a:{b:1}} * {a:{c:2}}", "[1,2] - [2]", "\"abc\" * 3", "\"abc\" * 0", "\"x\" / \"\"", "{} + {} | type",
    "null + null", "[] + null", "1 + \"a\"", "{} - {}", "[] * 2", "{a:1} | has(1)", "[1] | has(\"a\")", ".[\"a\"]?", ".a.b.c?",
    "try (.a.b.c) catch .", "[.[]?|.a?]", "(1,2) as $x | $x * 10", "[.[]?] | .[1.7]", "[1,2,3] | .[1.2:2.8]", "[range(10)] | .[2:4] = [\"x\"]",
    "\"abc\" | test(\"B\"; \"ix\")", "\"aXbXc\" | sub(\"x\"; \"-\"; \"gi\")", "\"abc\" | [match(\"\"; \"g\") | .offset]",
    "\"test 123 abc 456\" | [scan(\"\\\\d+\")]", "\"foo bar\" | [match(\"(?<w>\\\\w+)\"; \"g\") | .captures[0].name]",
    "\"a,b\" | split(\",\"; \"g\")", "\"ab\" | test(\"(\")", "\"ab\" | test(\"a\"; \"q\")", "splits(\"a\"; \"z\")?", "@sh \"echo \\(.)\"",
    "[.[]?] | @csv?", "[.[]?] | @tsv?", "input", "[inputs]", "$ARGS", "getpath([\"a\",\"b\"])?", "paths(..)?", "path(..)",
    "[path(.a, .b[0])]", "path(.a[].b)?", "try path(1) catch .", "path(first(.a,.b))", "[paths] | length", "limit(0; 1, 2)",
    "limit(-1; 1)?", "first(empty)?", "nth(-1; 1)?", "[.[]?] | sort_by(.k?) | length", "tostream | tojson", "getpath([]) | type",
    "splits(\"\")?", "ltrimstr(\"\")", "env.PATH | type", "$ENV.HOME | type", "@base32d?", "\"=\" | @base64d?", "\"YQ\" | @base64d",
    "\"a\" | @base64d?", "\"%zz\" | @urid?", "\"%41\" | @urid", "{\"a\":\"<&>\"} | @html \"x\\(.a)\"", "[1, \"a b\", null] | @sh",
    "{a:1} | @sh?", "[[1]] | @csv?", "[\"a\\tb\"] | @tsv", "[\"a\\\"b\"] | @csv", "tojson | test(\"\\\\[\")?",
    "def f: def g: 3; g * 2; f", "def f(x): x * 2; f(.a?)?", "def f($a; $b): $a + $b; f(1; 2)", "def fac: if . <= 1 then 1 else . * (. - 1 | fac) end; 10 | fac",
    "[.[]?] as [$a] | $a", ". as [$a, [$b]] | {$a, $b}", "{\"a\":1} as {$a} | $a", ". as {$a, b: [$c]} ?// $a | [$a, $c]?",
    "[\"a\",\"b\"] as [$x] | {$x: 1}?", "{(\"x\",\"y\"): (1,2)}", "{a: (1,2), b: (3,4)}", "{\"a b\": 1}.\"a b\"", "{$__loc__}",
    "\"\\(1;2)\"?", "[.[]?] | .[\"a\"]?", "ltrimstr(\"x\") | type", "@json \"\\(\"\\u0000\")\"", "\"\\u0000\" | tojson",
    "[splits(\"\\n\")]?", "getpath([\"a\",0])?", "\"x\" | ascii_downcase | ascii_upcase", "[.[]?] | min_by(.)?, max_by(.)?",
    "[3,1,2] | bsearch(2), bsearch(0), bsearch(4)", "[\"a\",\"b\"] | join(\"-\")", "[1,null,\"a\",true] | join(\",\")",
    "[[1]] | join(\",\")?", "[] | join(\",\")", "{\"a\":\"x\",\"b\":\"y\"} | join(\"\")", "[1,2] | join(1)?", "splits(\"[\")?",
    "halt_error?", "getpath(1)?", "error(\"x\") ?", ".[] |= empty", "[1,2,3] | .[] |= empty", "to_entries | map(.key) | add",
    "[range(3)] | add(.[] * 2)", "add(empty)", "[\"a\",\"b\"] | add", "[[1],[2]] | add", "[{a:1},{b:2}] | add", "[1,\"a\"] | add?",
    "@base64d | @base64?", "getpath([\"s\"]) | @base32 | @base32d", "[.[]?|tojson] | length", "infinite | tostring",
    "[infinite, -infinite, nan] | tojson", "[1,1.0,1.5,100,1e1,1E-3] | map(tostring)", "123456789012 | tostring",
    "1.7976931348623157e309", "[.[]?] | length as $n | $n", "getpath([\"b\", -1])", "if . then 1 end", "if empty then 1 else 2 end",
    "if (true, false) then \"a\" else \"b\" end", "if . == null then 1 elif . == 1 then 2 else 3 end", "[.[]?] | any(. == 1)",
    "[.[]?] | all(type == \"number\")", "isempty(empty), isempty(1)", "[range(10)] | .[2:8:2]?", "splits(null)?",
    "\"abc\" | .[0:1] = \"x\"", "[1,2] | .[0:1] = 3", "{a:1} | .[0]?", "1 as $x | 2 as $y | [$x, $y, $__loc__]",
    "[limit(5; recurse(. + 1; . < 3))]?", "getpath([\"a\"]) |= 3", "paths(type == \"array\")", "[..] | map(type) | unique",
    "tostream | select(length == 2) | .[0] | join(\".\")?", "{} | .a += 1", "{} | .a -= 1", "{} | .a *= 2", "{a: 2} | .a /= 0",
    "{a: 7} | .a %= 0", "[1, 2] | .[] *= 2", "{\"a\":[1,2]} | del(.a[])", "[1,2,3] | del(.[1:])", "[1,2,3] | delpaths([[5]])",
    "{} | delpaths([[\"a\",\"b\"]])", "1 | delpaths([[\"a\"]])?", "getpath([\"a\"]) as [$x] | $x?", "\"a\" as $x | $x[0]?",
    "splits(\"a\") as $x | $x?", "to_entries | map(select(.value | type == \"number\")) | from_entries",
    "[{\"name\":\"a\",\"value\":1},{\"k\":\"b\",\"v\":2},{\"key\":null,\"value\":3},{\"key\":false},{\"key\":1,\"value\":2}] | from_entries?",
    "@uri \"https://x/?q=\\(.s?)\"", "input_line_number", "getpath([\"t\"]) | not", "[true, false, null, 0, \"\"] | map(not)",
    "\"\\(1)\\(2)\" | tonumber", "[.[]?] | tojson | fromjson == .", "ltrimstr(\"a\") | ltrimstr(\"b\")", "significand", "logb",
    "gamma", "lgamma_r", "frexp", "modf", "[1,2] | ldexp(.[0]; .[1])", "[10, 3] | pow(.[0]; .[1]), log10, exp10?", "nearbyint, trunc, round, ceil, rint",
    "drem(10; 3), nexttoward(1; 2), scalb(1; 3), scalbln(1; 3), fma(2; 3; 4), fmin(1; 2), fmax(1; 2), fdim(5; 3), copysign(3; -1)",
    "j0, j1, y0?, y1?, jn(2; .)?, yn(2; .)?", "[1.5,-1.5,2.5,-0.5] | map(round)", "1e300 * 1e300", "-(1e300 * 1e300)",
    "[splits(\", \")] | length", "@json, @text | length", "tojson | ascii", "getpath([\"s\"]) | test(\"\\\\p{Lu}\")",
    "\"aAbB\" | [match(\"[a-z]\"; \"g\").string]", "\"a\\nb\" | [match(\"^b\"; \"g\").offset], [match(\"a$\").offset], test(\"a.b\"; \"s\"), test(\"a.b\"; \"m\")",
    "\"abc\" | sub(\"(?<x>b)\"; \"[\\(.x)]\"; \"g\")", "\"aaa\" | gsub(\"a\"; \"b\", \"c\")", "\"abc\" | [sub(\"(?<x>.)\"; \"\\(.x)\\(.x)\", \"-\")]",
    "\"abab\" | [match(\"(a)(x)?\"; \"g\") | .captures | map(.offset)]", "\"😀a\" | [match(\".\"; \"g\") | [.offset, .length]]",
]
INPUTS = [DOC, ARR, OBJS, "null", '"Hello, World"', "1425599507", "3", "[]", "{}", '"aé😀"']

# Whole command lines: (arguments, stdin, extra environment).
CLI = [
    (["."], "1 2 [3] {\"a\":4}", {}),
    (["-c", "."], "[1, {\"a\" : [2,3]}]", {}),
    (["--tab", "."], "{\"a\":[1,{}]}", {}),
    (["--indent", "3", "."], "{\"a\":[1,{\"b\":2}]}", {}),
    (["--indent", "0", "."], "{\"a\":[1]}", {}),
    (["--indent", "8", "."], "1", {}),
    (["--indent"], "1", {}),
    (["-S", "-c", "."], "{\"b\":1,\"a\":{\"d\":1,\"c\":2}}", {}),
    (["-a", "."], "\"aé😀\\u0001\"", {}),
    (["-r", ".[]"], "[\"a\",\"b\\nc\",1,null]", {}),
    (["-j", ".[]"], "[\"a\",\"b\",1]", {}),
    (["--raw-output0", ".[]"], "[\"a\",\"b\"]", {}),
    (["--raw-output0", ".[]"], "[\"a\",\"c\\u0000d\"]", {}),
    (["-C", "."], "{\"a\":[1,\"x\",null,true,false,{}],\"b\":{\"c\":1.5}}", {}),
    (["-C", "-c", "."], "{\"a\":[1,\"x\",null,true,false,{}]}", {}),
    (["-C", "."], "[1]", {"JQ_COLORS": "4;31:0;32"}),
    (["-C", "."], "[1]", {"JQ_COLORS": "garbage"}),
    (["-n", "1+1"], "", {}),
    (["-n", "[inputs]"], "1 2 3", {}),
    (["-n", "input, input"], "1 2 3", {}),
    (["-n", "input, input"], "1", {}),
    (["-s", "."], "1 2 3", {}),
    (["-s", "."], "", {}),
    (["-R", "."], "a\nb\n\nc", {}),
    (["-Rs", "."], "a\nb\n\nc", {}),
    (["-Rn", "[inputs]"], "a\nb", {}),
    (["-e", "."], "null", {}),
    (["-e", "."], "false", {}),
    (["-e", "."], "1", {}),
    (["-e", "empty"], "1", {}),
    (["-e", ".[]"], "[1, null]", {}),
    (["-e", "error"], "\"x\"", {}),
    ([".a"], "\"x\" 1", {}),
    ([".+1"], "\"a\" 1", {}),
    ([".+1"], "1 \"a\"", {}),
    (["."], "{", {}),
    (["."], "[1,2", {}),
    (["."], "1 2 {", {}),
    (["."], "{\"a\":1,}", {}),
    (["."], "nan", {}),
    (["."], "[NaN, Infinity, -Infinity, infinity]", {}),
    (["."], "\"\\ud800\"", {}),
    (["."], "\"\\x\"", {}),
    (["."], "tru", {}),
    (["."], "1.e3 -1 .5", {}),
    (["."], "100000000000000000000000000000001 1.000000000000000000001 1E1000 -0 0.00", {}),
    (["--seq", "."], "\x1e1\x1e[2]\x1e{\"a\"", {}),
    (["--seq", "-c", "."], "1 2", {}),
    (["--stream", "-c", "."], "{\"a\":[1,{\"b\":2}],\"c\":[]}", {}),
    (["--stream", "-c", "."], "[1,[2", {}),
    (["--stream-errors", "-c", "."], "[1,[2", {}),
    (["-c", "--stream", "fromstream(inputs)", "-n"], "{\"a\":[1,2]} [3]", {}),
    (["-c", "tostream"], "{\"a\":[1,{\"b\":null}]}", {}),
    (["--arg", "x", "1", "-n", "$x"], "", {}),
    (["--argjson", "x", "{\"a\":1}", "-n", "$x.a"], "", {}),
    (["--argjson", "x", "{bad", "-n", "$x"], "", {}),
    (["-n", "$ARGS", "--args", "a", "b"], "", {}),
    (["-n", "$ARGS", "--jsonargs", "1", "{\"a\":2}"], "", {}),
    (["-n", "$ARGS", "--jsonargs", "1", "{bad"], "", {}),
    (["-n", "--arg", "x", "1", "--arg", "x", "2", "$x, $ARGS.named"], "", {}),
    (["-n", "$y"], "", {}),
    (["-n", "foo"], "", {}),
    (["-n", "foo(1)"], "", {}),
    (["-n", "1 +"], "", {}),
    (["-n", ". as [$a, $b] | $c"], "", {}),
    (["-n", "if"], "", {}),
    (["-n", "{(1):2}"], "", {}),
    (["-n", "\"\\(1"], "", {}),
    (["-n", "[1,2,3"], "", {}),
    (["-n", "include \"nonexistent\"; 1"], "", {}),
    (["-n", "import \"a\" as a; a::a"], "", {}),
    (["-L", MODS, "-n", "import \"a\" as a; a::a"], "", {}),
    (["-L", MODS, "-n", "include \"c\"; [a, c]"], "", {}),
    (["-L", MODS, "-n", "import \"data\" as $d; $d"], "", {}),
    (["-L", MODS, "-n", "\"c\" | modulemeta"], "", {}),
    (["-L", MODS, "-nc", "\"syntaxerror\" | modulemeta"], "", {}),
    (["-L", MODS, "-n", "import \"syntaxerror\" as e; 1"], "", {}),
    (["-L", MODS, "-n", "import \"cycle_a\" as a; 1"], "", {}),
    (["-n", "halt"], "", {}),
    (["-n", "\"bye\\n\" | halt_error"], "", {}),
    (["-n", "{a:1} | halt_error"], "", {}),
    (["-n", "\"x\" | halt_error(1)"], "", {}),
    (["-n", "null | halt_error(0)"], "", {}),
    (["-n", "1 | halt_error(\"x\")"], "", {}),
    (["-n", "error"], "", {}),
    (["-n", "error({a:1})"], "", {}),
    (["-n", "error(null)"], "", {}),
    (["-n", "\"x\" | error"], "", {}),
    (["-n", "1, error(\"e\"), 2"], "", {}),
    (["-n", "[1,2] | debug | length"], "", {}),
    (["-n", "\"a\" | stderr | length"], "", {}),
    (["-n", "{a:1} | stderr | empty"], "", {}),
    (["-n", "input_filename"], "", {}),
    ([".", "/nonexistent"], "", {}),
    (["-n", "$__prog_args"], "", {}),
    (["-n", "[limit(3; repeat(1))]"], "", {}),
    (["-n", "reduce range(100000) as $i (0; . + $i)"], "", {}),
    (["-n", "[range(1000)] | map(tostring) | join(\",\") | length"], "", {}),
    (["-n", "def f: if . < 2000 then . + 1 | f else . end; 0 | f"], "", {}),
    (["-n", "[range(5000)] | reduce .[] as $x ([]; . + [$x]) | length"], "", {}),
    (["-rn", "@sh \"echo \\(\"a'b\")\""], "", {}),
    (["-n", "now | type"], "", {}),
    (["-n", "1731627341 | strflocaltime(\"%F %T %z %Z\")"], "", {"TZ": "Asia/Tokyo"}),
    (["-n", "1731627341 | localtime"], "", {"TZ": "Europe/Paris"}),
    (["-n", "\"2024-11-15 08:35:41\" | strptime(\"%Y-%m-%d %H:%M:%S\") | mktime"], "", {"TZ": "Asia/Tokyo"}),
    (["-n", "$ENV.JQTEST"], "", {"JQTEST": "yes"}),
    (["-n", "env.JQTEST"], "", {"JQTEST": "yes"}),
    (["-n", "get_search_list"], "", {}),
    (["-L", "/x", "-L/y", "-n", "get_search_list"], "", {}),
    (["--unknown"], "", {}),
    (["-Z", "."], "", {}),
    (["-nr", "\"a\\u0000b\""], "", {}),
    (["-n", "\"\\u0000\" | tojson"], "", {}),
    ([".", "-"], "1", {}),
    (["--", "-n"], "", {}),
    (["-nc", "[.,1]", "--args"], "", {}),
    (["-nc", "$__loc__"], "", {}),
    (["-n", "[splits(\"a\";\"b\";\"c\")]"], "", {}),
    (["-n", "{} | .a.b.c |= 1"], "", {}),
    (["-n", "1 as $x | [$x, $x] | .[$x]"], "", {}),
    (["-n", "[1,2,3] | IN(2, 4)"], "", {}),
    (["-n", "\"abc\" | ascii_downcase | @base32"], "", {}),
    (["-n", "[paths]"], "", {}),
    (["-n", "try (1/0) catch ."], "", {}),
    (["-n", "1/0"], "", {}),
    (["-n", "0/0"], "", {}),
    (["-n", "[.[]?]"], "", {}),
    (["-n", "{a:1} | .[]"], "", {}),
    (["-n", "1 | .[]"], "", {}),
    (["-n", "\"x\" | .a"], "", {}),
    (["-n", "{} | .[0]"], "", {}),
    (["-n", "[] | .a"], "", {}),
    (["-n", "[] | .[\"a\"] = 1"], "", {}),
    (["-n", "{} | .[0] = 1"], "", {}),
    (["-n", "[1] | implode"], "", {}),
    (["-n", "[-1, 1114112, 55296] | implode | explode"], "", {}),
    (["-n", "[\"a\"] | implode"], "", {}),
    (["-n", "\"very-long-long-long-long-string\" | -."], "", {}),
    (["-n", "{\"a\":\"very-long-long-long-long-string\"} | -."], "", {}),
    (["-n", "[1,2,3,4,5,6,7,8,9,10,11,12,13] | -."], "", {}),
    (["-n", "\"ééééééééééééééééééééééééééééé\" | -."], "", {}),
    (["-n", "\"abc\" | test(\"(\")"], "", {}),
    (["-n", "\"abc\" | test(1)"], "", {}),
    (["-n", "\"abc\" | ltrimstr(1)"], "", {}),
    (["-n", "1 | ascii_downcase"], "", {}),
    (["-n", "{} | keys | .[0] | ascii"], "", {}),
    (["-n", "1 | @base64d"], "", {}),
    (["-n", "[1] | @tsv, @csv"], "", {}),
    (["-n", "[[1]] | @csv"], "", {}),
    (["-n", "{} | @sh"], "", {}),
    (["-n", "1 | fromjson"], "", {}),
    (["-n", "\"[\" | fromjson"], "", {}),
    (["-n", "1 | tonumber, (\"1x\" | tonumber)"], "", {}),
    (["-n", "{} | sort"], "", {}),
    (["-n", "{} | keys, (1 | keys)"], "", {}),
    (["-n", "1 | length, (true | length)"], "", {}),
    (["-n", "[1,2] | has(\"a\")"], "", {}),
    (["-n", "{} | contains(1)"], "", {}),
    (["-n", "\"a\" | split(1)"], "", {}),
    (["-n", "1 | startswith(\"a\")"], "", {}),
    (["-n", "[3,1] | sort_by(error(\"x\"))"], "", {}),
    (["-n", "[1] | min_by(1, 2)"], "", {}),
    (["-n", "\"x\" | strptime(1)"], "", {}),
    (["-n", "\"x\" | strptime(\"%Y\")"], "", {}),
    (["-n", "\"x\" | mktime"], "", {}),
    (["-n", "[\"a\"] | mktime"], "", {}),
    (["-n", "\"x\" | gmtime"], "", {}),
    (["-n", "1 | strftime(1)"], "", {}),
    (["-n", "\"x\" | strftime(\"%Y\")"], "", {}),
    (["-n", "1 | test(\"a\")"], "", {}),
    (["-n", "\"a\" | sub(1; \"b\")"], "", {}),
    (["-n", "[limit(-1; 1)]"], "", {}),
    (["-n", "[nth(-1; 1)]"], "", {}),
    (["-n", "[1] | flatten(-1)"], "", {}),
    (["-n", "[range(1; \"a\")]"], "", {}),
    (["-n", "{} | splits(\"a\")"], "", {}),
    (["-n", "$__loc__ | .file"], "", {}),
    (["-n", "getpath([\"a\", 1])"], "", {}),
    (["-n", "{a: 1} | getpath([\"a\", \"b\"])"], "", {}),
    (["-n", "1 | setpath([\"a\"]; 1)"], "", {}),
    (["-n", "null | setpath([-1]; 1)"], "", {}),
    (["-n", "[1] | delpaths([[\"a\"]])"], "", {}),
    (["-n", "[1] | delpaths(0)"], "", {}),
    (["-n", "path(1)"], "", {}),
    (["-n", "[1] | path(.[] | . + 1)"], "", {}),
    (["-n", "{} | path(.a | first(.b, .c))"], "", {}),
    (["-n", "[[1,2]] | path(.. | select(type == \"number\"))"], "", {}),
    (["-n", "{a:[1]} | paths(type == \"number\")"], "", {}),
    (["-n", "[1,[2]] | getpath(paths)"], "", {}),
    (["-n", "{} | .a |= error(\"x\")"], "", {}),
    (["-n", "[1,2,3] | (.[] | select(. > 1)) |= empty"], "", {}),
    (["-n", "[[1,2],[3]] | .[][] += 1"], "", {}),
    (["-n", "{a:{b:1}} | to_entries"], "", {}),
    (["-n", "[{\"key\":\"a\"}] | from_entries"], "", {}),
    (["-n", "{a:1} | with_entries(.key |= ascii_upcase)"], "", {}),
    (["-n", "[{a:1,b:2},{a:1,b:3}] | group_by(.a) | map(map(.b))"], "", {}),
    (["-n", "[{a:1,b:2},{a:3,b:1}] | sort_by(.b, .a)"], "", {}),
    (["-n", "[1,[2,[3]]] | getpath([1,1,0])"], "", {}),
    (["-n", "[3,2,1] | sort | bsearch(2)"], "", {}),
    (["-n", "{a:[{b:1},{b:2}]} | [.a[].b] | add"], "", {}),
    (["-n", "\"a-b-c\" | split(\"-\") | join(\"+\")"], "", {}),
    (["-n", "\"Hello\" | [splits(\"l\")]"], "", {}),
    (["-n", "[splits(\"a\")]"], "", {}),
    (["-n", "input_line_number"], "", {}),
    (["input_line_number"], "1\n2\n\n3", {}),
    (["-c", "[., input_line_number]"], "{\"a\":\n1}\n[2]\n3", {}),
    (["-c", "input_filename"], "1", {}),
    (["-n", "[1,2,3] | .[1:] = [\"x\"] | .[0] += 1"], "", {}),
    (["-n", "[range(10)] | .[2:4] |= map(. * 10)"], "", {}),
    (["-n", "\"abc\" | .[1:] |= \"x\""], "", {}),
    (["-n", "[.[]?] | .[1:2] = 1"], "", {}),
    (["-n", "builtins | map(select(startswith(\"to\"))) | sort"], "", {}),
    (["-n", "builtins | length"], "", {}),
    (["-n", "\"\\(1, 2) \\(3, 4)\""], "", {}),
    (["-n", "{a: 1, b: 2} | {a, $__loc__, \"c\": 3, (\"d\"): 4, @text \"e\": 5}"], "", {}),
    (["-n", "{if: 1, then: 2, reduce: 3} | .if, .then, .reduce"], "", {}),
    (["-n", "def keys: 1; keys"], "", {}),
    (["-n", "def f(g): [g]; f(1, 2)"], "", {}),
    (["-n", "def f: reduce .[] as $x (0; . + $x); [1, 2] | f"], "", {}),
    (["-n", "[foreach range(5) as $x (0; . + $x; [$x, .])]"], "", {}),
    (["-n", "[foreach range(5) as [$x] (0; . + 1)]"], "", {}),
    (["-n", "reduce empty as $x (0; . + 1)"], "", {}),
    (["-n", "reduce (1, 2) as $x (0; ., 10)"], "", {}),
    (["-n", "reduce (1, 2) as $x (0; empty)"], "", {}),
    (["-n", "[foreach (1, 2) as $x (0; empty; .)]"], "", {}),
    (["-n", "[label $out | 1, break $out, 2]"], "", {}),
    (["-n", "[.[]?] | first"], "", {}),
    (["-n", "try error catch ."], "", {}),
    (["-n", "try error(null) catch ."], "", {}),
    (["-n", "[.[]?] | try error(\"\\(.)\") catch ."], "", {}),
    (["-n", "(try error(\"x\") catch .) | ascii_upcase"], "", {}),
    (["-n", "try (1, error(\"x\"), 2) catch ."], "", {}),
    (["-n", "[(1, 2) | try (if . == 1 then error(\"x\") else . end)]"], "", {}),
    (["-n", ".a?.b?"], "", {}),
    (["-n", "[1] | .[0]?"], "", {}),
    (["-n", "1?"], "", {}),
    (["-n", "[\"a\",1] | .[] as $x ?// [$x] | $x"], "", {}),
    (["-n", "[[1,2]] | .[] as [$a] ?// $a | $a"], "", {}),
    (["-n", "{} as [$a] ?// {a: $a} | $a"], "", {}),
    (["-n", "[[3]] | .[] as [$a] ?// [$b] | if $a != null then error(\"x\") else $b end"], "", {}),
    (["-c", "-n", "{\"a\":1,\"b\":2} | to_entries[] | {(.key): .value}"], "", {}),
    (["-n", "\"\\u00e9\" | ascii_downcase, ascii_upcase, explode"], "", {}),
    (["-n", "[\"\\u0041\", \"\\ud83d\\ude00\"] | map(explode)"], "", {}),
    (["-n", "\"x\" | ltrimstr(\"x\"), rtrimstr(\"x\"), trimstr(\"x\")"], "", {}),
    (["-n", "[1, 1.0, 1.00, 1e0] | unique"], "", {}),
    (["-n", "[1.000, 2.50] | map(tojson)"], "", {}),
    (["-n", "1.000 | ., -., . + 0, . * 1, [.]"], "", {}),
    (["-n", "100000000000000000000000000001 | ., . == 100000000000000000000000000000, tojson, tostring"], "", {}),
    (["-n", "[0.1, 1e-7, 1e17, 1.5e300, 5e-324, 123456789.123456789]"], "", {}),
    (["-n", "[3, 1e1000] | sort"], "", {}),
    (["-n", "-1e1000 < 1e1000"], "", {}),
    (["-n", "[nan, 1, null] | sort"], "", {}),
    (["-n", "nan < nan, nan == nan, nan > 1, [nan] == [nan]"], "", {}),
    (["-n", "[nan] | min, max"], "", {}),
    (["-n", "{} | .[\"\\u0000\"] = 1 | keys"], "", {}),
    (["-n", "\"\\u001f\\u007f\\u0080\""], "", {}),
    (["-n", "@text \"\\(\"\\u001f\")\""], "", {}),
    (["--tab", "-n", "{a:[{b:1}]}"], "", {}),
    (["-n", "--indent", "1", "[[[]]]"], "", {}),
    (["-n", "{} | .a.b |= . + 1"], "", {}),
    (["-n", "[{}] | .[0].a.b = 1"], "", {}),
    (["-n", "null | .[1:3] = [1]"], "", {}),
    (["-n", "[1,2,3] | .[-5:-1]"], "", {}),
    (["-n", "[1,2,3] | .[null:2], .[1:null]"], "", {}),
    (["-n", "[1,2,3] | .[\"a\":]"], "", {}),
    (["-n", "\"abcdef\" | .[2:-2], .[10:], .[-100:2]"], "", {}),
    (["-n", "[1,2,3] | .[nan], .[infinite], .[-infinite]"], "", {}),
    (["-n", "[1,2,3] | .[1e300] = 1"], "", {}),
    (["-n", "[] | .[1e9] = 1"], "", {}),
    (["-n", "{} | has(nan)"], "", {}),
    (["-n", "[1] | has(nan), has(-1), has(0.5)"], "", {}),
    (["-n", "[1,2] | indices(1), indices([1,2]), index([2]), (\"abab\" | indices(\"ab\"))"], "", {}),
    (["-n", "[] | indices([])"], "", {}),
    (["-n", "\"a\" | indices(\"\")"], "", {}),
    (["-n", "{} | tostream"], "", {}),
    (["-n", "[[],{}] | [tostream]"], "", {}),
    (["-n", "[fromstream(([0], 1), ([1], 2), [[1]])]"], "", {}),
    (["-n", "[1|truncate_stream([[0],1],[[1,0],2],[[1,0]],[[1]])]"], "", {}),
    (["-n", "getpath([\"a\"]) | getpath([\"b\"])"], "", {}),
    (["-n", "ltrimstr(\"a\")"], "", {}),
    (["-n", "[.[]?] | add"], "", {}),
    (["-n", "{} | .[\"a\",\"b\"] = 1"], "", {}),
    (["-n", "[1, 2] | .[0, 1] |= . * 2"], "", {}),
    (["-n", "[[1,2],[3,4]] | map(add) | add"], "", {}),
    (["-n", "\"a,b, c\" | split(\", *\"; null)"], "", {}),
    (["-n", "\"test\" | ascii(1)?"], "", {}),
    (["-n", "@json \"\\([1, \"a\"])\" | fromjson"], "", {}),
    (["-n", "{\"a\":1} | tojson | @json"], "", {}),
    (["-n", "[\"a\", 1, null] | @text, @json, @csv, @tsv, @html, @sh, @uri"], "", {}),
    (["-n", "\"<script>'&\\\"\" | @html"], "", {}),
    (["-n", "\"ü é/?=&\" | @uri, (@uri | @urid)"], "", {}),
    (["-n", "\"\\u0000\\u00ff\" | @base64 | ., @base64d"], "", {}),
    (["-n", "\"YWJj\" | @base64d, (\"YWJ\" | @base64d), (\"YW\" | @base64d), (\"Y\" | @base64d)"], "", {}),
    (["-n", "\"ab\" | @base32, (@base32 | @base32d)"], "", {}),
    (["-n", "1 | @base32d"], "", {}),
    (["-n", "\"MFRA====\" | @base32d"], "", {}),
    (["-n", "@foo"], "", {}),
    (["-n", "1 | @foo \"x\""], "", {}),
    (["-n", "[.[]?] | @csv \"\\(.)\""], "", {}),
    (["-n", "\"x\" | test(\"\\\\h\")"], "", {}),
    (["-n", "\"a1 b2\" | [match(\"(?<l>[a-z])(?<d>\\\\d)\"; \"g\") | .captures | map({(.name): .string}) | add]"], "", {}),
    (["-n", "\"aaa\" | [match(\"a*?\"; \"g\")] | length"], "", {}),
    (["-n", "\"Ab\" | test(\"ab\"; \"i\"), test(\"a b\"; \"x\"), test(\"A\"; \"\")"], "", {}),
    (["-n", "\"abc\" | capture(\"(?<x>z)?\")"], "", {}),
    (["-n", "\"x y\" | sub(\" \"; \"\\n\") | @json"], "", {}),
    (["-n", "\"aXbX\" | [splits(\"x\"; \"i\")]"], "", {}),
    (["-n", "\"ab\" | gsub(\"(?<c>.)\"; \"\\(.c|ascii_upcase)\")"], "", {}),
    (["-n", "\"abc\" | gsub(\"b\"; \"\")"], "", {}),
    (["-n", "\"abc\" | gsub(\"^\"; \">\"), gsub(\"$\"; \"<\")"], "", {}),
    (["-n", "\"a.b\" | split(\".\")"], "", {}),
    (["-n", "\"a1b22c\" | [scan(\"[0-9]+\"), scan(\"([a-z])([0-9]*)\")]"], "", {}),
    (["-n", "\"ab\" | [match(\"(a)|(b)\"; \"g\") | .captures | map(.string)]"], "", {}),
    (["-n", "\"ab\" | test(\"\\\\p{L}\"), test(\"[[:alpha:]]\"), test(\"\\\\w\\\\b\")"], "", {}),
    (["-n", "\"foo\" | test(\"foo\"; \"gnlxsp\")"], "", {}),
]

KNOWN = set()


def run(binary, args, stdin, env):
    e = dict(os.environ)
    e.pop("JQ_COLORS", None)
    e.pop("NO_COLOR", None)
    e.update(env)
    with tempfile.TemporaryDirectory() as d:
        r = subprocess.run([binary] + args, input=stdin.encode(), capture_output=True, env=e, cwd=d, timeout=60)
    err = r.stderr.decode(errors="replace").replace(binary, "jq")
    return r.returncode, r.stdout.decode(errors="replace"), err


def main():
    cases = [(["-c", f], i, {}) for f in FILTERS for i in INPUTS] + CLI
    bad = 0
    for args, stdin, env in cases:
        a = run(OURS, args, stdin, env)
        b = run(REF, args, stdin, env)
        key = " ".join(args) + " <<< " + stdin[:40]
        if a != b and key not in KNOWN:
            bad += 1
            print(f"DIFF: jq {args!r} <<< {stdin[:60]!r} {env or ''}")
            for what, x, y in zip(("status", "stdout", "stderr"), a, b):
                if x != y:
                    print(f"  {what}:\n    ours: {str(x)[:600]!r}\n    ref:  {str(y)[:600]!r}")
    print(f"{len(cases) - bad} of {len(cases)} cases identical")
    sys.exit(1 if bad else 0)


main()
